export interface ChunkingOptions {
  maxChunkSize: number;
  overlap: number;
}

export interface RawChunk {
  content: string;
  chunkIndex: number;
  sectionTitle?: string;
  pageStart?: number;
}

export class ContextAwareChunker {
  constructor(private options: ChunkingOptions = { maxChunkSize: 1000, overlap: 200 }) {}

  chunkText(text: string): RawChunk[] {
    // 1. Split by double newlines (paragraphs)
    const paragraphs = text.split(/\n\s*\n/);
    
    const chunks: RawChunk[] = [];
    let currentChunk = "";
    let currentSection = "";
    let chunkIndex = 0;
    let currentPage = 1;

    for (let i = 0; i < paragraphs.length; i++) {
      let p = paragraphs[i].trim();
      if (!p) continue;

      // Check for page markers generated by pdf-parse pagerender
      const pageMatch = p.match(/---PAGE_START_(\d+)---/);
      if (pageMatch) {
        currentPage = parseInt(pageMatch[1], 10);
        p = p.replace(/---PAGE_START_\d+---/g, "").replace(/---PAGE_END_\d+---/g, "").trim();
        if (!p) continue;
      }

      // Extremely naive header detection for context
      if (p.startsWith("#") || p.match(/^[A-Z0-9][A-Z0-9\s]+$/)) {
        currentSection = p.substring(0, 50).replace(/^#+\s*/, "");
      }

      if (currentChunk.length + p.length > this.options.maxChunkSize && currentChunk.length > 0) {
        // Push current chunk
        chunks.push({
          content: currentChunk.trim(),
          chunkIndex: chunkIndex++,
          sectionTitle: currentSection || undefined,
          pageStart: currentPage
        });

        // Start new chunk with overlap
        // Take the last overlap characters of the current chunk, ideally breaking at a word
        const overlapStart = Math.max(0, currentChunk.length - this.options.overlap);
        const overlapText = currentChunk.substring(overlapStart);
        const lastSpace = overlapText.indexOf(" ");
        currentChunk = (lastSpace > 0 ? overlapText.substring(lastSpace) : overlapText) + "\n\n" + p;
      } else {
        currentChunk = currentChunk ? currentChunk + "\n\n" + p : p;
      }
    }

    if (currentChunk.trim().length > 0) {
      chunks.push({
        content: currentChunk.trim(),
        chunkIndex: chunkIndex++,
        sectionTitle: currentSection || undefined,
        pageStart: currentPage
      });
    }

    return chunks;
  }
}
